### ISSUE TITLE
Extract then remove conversion / bundling code

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#151]
Remove all bundling / conversion related code from this repo once the following items land, **minimally**:

* [x] jupyter-incubator/dashboards_bundlers#1 (*Deploy as -> Local Dashboard*, still using Thebe)
* [x] jupyter-incubator/dashboards_bundlers#5 (*Download as -> PHP Dashboard bundle (.zip)*, still using Thebe)
* [x] jupyter-incubator/contentmanagement#20 (*Download as -> Notebook bundle (.zip)*, notebook + associated files)

Make this repo solely about developing dashboard layouts and previewing the results within the notebook UI.

**Comment by parente** [comment]
Extracted to other packages as noted. Released those packages. Ready to merge here and release 0.3.0 as best I can tell.
